export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_COMMENT = 'ADD_COMMENT';
export const INCREMENT_QUESTION_UPS = 'INCREMENT_QUESTION_UPS';
export const INCREMENT_QUESTION_DOWNS = 'INCREMENT_QUESTION_DOWNS';
export const INCREMENT_COMMENT_UPS = 'INCREMENT_COMMENT_UPS';
export const INCREMENT_COMMENT_DOWNS = 'INCREMENT_COMMENT_DOWNS';